# playbook register node_exporter to consul
# ansible-playbook  register_consul.yaml  -e "host_group=suzhou" -e "consul_server=61.155.137.69" -e "CONSUL_HTTP_TOKEN=${CONSUL_HTTP_TOKEN}" --limit 10.10.10.1
- # hosts 通过指定变量传入
  hosts: "{{ host_group }}"
  tasks:
    - name: 判断是否设置node_exporter_scrape_ip变量
      assert:
        that:
          - node_exporter_scrape_ip is defined
      failed_when: node_exporter_scrape_ip is not defined

    - name: 判断是否设置consul_server变量
      assert:
        that:
          - consul_server is defined
      failed_when: consul_server is not defined

    - name: 宿主机上发送curl
      delegate_to: localhost
      register: result
      ansible.builtin.uri:
        url: http://{{ consul_server }}:8500/v1/agent/service/register
        method: PUT
        body_format: json
        headers:
          X-Consul-Token: "{{ CONSUL_HTTP_TOKEN }}"
        body:
          id: "node_exporter-{{ node_exporter_scrape_ip }}"
          name: "node_exporter-{{ node_exporter_scrape_ip }}"
          tags: ["node_exporter"]
          address: "{{ node_exporter_scrape_ip }}"
          port: 9100
          meta:
            project: "operator"
          checks:
            - http: "http://{{ health_check_ip }}:9100/metrics"
              interval: "10s"
              timeout: "5s"

    - debug:
        msg: "curl 相应内容: {{ result }}"
